# install-aristotle.ps1 — Install Aristotle error reflection agent (Windows)
# Usage: powershell -ExecutionPolicy Bypass -File install-aristotle.ps1

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SkillSrc = $ScriptDir

$OpenCodeConfig = if ($env:OPENCODE_CONFIG_DIR) { $env:OPENCODE_CONFIG_DIR } else { Join-Path $env:USERPROFILE '.config\opencode' }
$ClaudeConfig = Join-Path $env:USERPROFILE '.claude'

Write-Host ""
Write-Host "🦉 Aristotle — Error Reflection & Learning Agent" -ForegroundColor Blue
Write-Host "══════════════════════════════════════════════════"
Write-Host ""

# Step 1: Install skill files
$SkillDest = Join-Path $OpenCodeConfig 'skills\aristotle'
Write-Host "[1/4] Installing Aristotle skill to $SkillDest..." -ForegroundColor Cyan

New-Item -ItemType Directory -Path (Join-Path $SkillDest 'hooks') -Force | Out-Null
Copy-Item (Join-Path $SkillSrc 'SKILL.md') (Join-Path $SkillDest 'SKILL.md') -Force
Copy-Item (Join-Path $SkillSrc 'hooks\aristotle-reflector.sh') (Join-Path $SkillDest 'hooks\aristotle-reflector.sh') -Force
Copy-Item (Join-Path $SkillSrc 'hooks\aristotle-reflector.ps1') (Join-Path $SkillDest 'hooks\aristotle-reflector.ps1') -Force
Write-Host "✓ Skill files installed." -ForegroundColor Green

# Step 2: Initialize learnings file
$LearningsFile = Join-Path $ClaudeConfig 'rules\aristotle-learnings.md'
if (-not (Test-Path $LearningsFile)) {
    Write-Host "[2/4] Initializing learnings file at $LearningsFile..." -ForegroundColor Cyan
    New-Item -ItemType Directory -Path (Join-Path $ClaudeConfig 'rules') -Force | Out-Null
    @"
# Aristotle Learnings (User-Level)

<!-- Auto-generated by Aristotle. Append-only. Do not reorganize. -->
<!-- This file is automatically injected into sessions via the rules-injector hook. -->
<!-- Rules written here apply across ALL projects. -->

"@ | Set-Content $LearningsFile -Encoding UTF8
    Write-Host "✓ Learnings file created." -ForegroundColor Green
} else {
    Write-Host "[2/4] Learnings file already exists — preserving." -ForegroundColor Cyan
}

# Step 3: Configure Stop hook
$SettingsFile = Join-Path $ClaudeConfig 'settings.json'
$HookCmd = "powershell -ExecutionPolicy Bypass -File `"$SkillDest\hooks\aristotle-reflector.ps1`""

Write-Host "[3/4] Configuring Stop hook for auto-detection..." -ForegroundColor Cyan

if (Test-Path $SettingsFile) {
    $content = Get-Content $SettingsFile -Raw
    if ($content -match 'aristotle-reflector') {
        Write-Host "✓ Stop hook already configured." -ForegroundColor Green
    } else {
        Write-Host "⚠ $SettingsFile exists but Aristotle hook not found." -ForegroundColor Yellow
        Write-Host "  Add this to the 'hooks.Stop' section:"
        Write-Host "  {"
        Write-Host '    "type": "command",'
        Write-Host "    `"command`": `"$HookCmd`""
        Write-Host "  }"
    }
} else {
    Write-Host "⚠ No settings.json found. Creating with Aristotle Stop hook..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $ClaudeConfig -Force | Out-Null
    $settings = @{
        hooks = @{
            Stop = @(
                @{
                    matcher = ""
                    hooks = @(
                        @{
                            type = "command"
                            command = $HookCmd
                        }
                    )
                }
            )
        }
    }
    $settings | ConvertTo-Json -Depth 10 | Set-Content $SettingsFile -Encoding UTF8
    Write-Host "✓ Stop hook configured." -ForegroundColor Green
}

# Step 4: Verify
Write-Host "[4/4] Verifying installation..." -ForegroundColor Cyan
$errors = 0

if (-not (Test-Path (Join-Path $SkillDest 'SKILL.md'))) { $errors++; Write-Host "✗ SKILL.md not found" -ForegroundColor Red }
if (-not (Test-Path (Join-Path $SkillDest 'hooks\aristotle-reflector.ps1'))) { $errors++; Write-Host "✗ Reflector script not found" -ForegroundColor Red }
if (-not (Test-Path $LearningsFile)) { $errors++; Write-Host "✗ Learnings file not found" -ForegroundColor Red }

if ($errors -eq 0) {
    Write-Host "✓ All files verified." -ForegroundColor Green
}

Write-Host ""
Write-Host "══════════════════════════════════════════════════"
Write-Host "🦉 Aristotle installed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Usage:"
Write-Host "  • Type /aristotle in any OpenCode session to reflect on errors"
Write-Host "  • The Stop hook will auto-detect error corrections and prompt you"
Write-Host "  • Learnings are written to $LearningsFile"
Write-Host "  • Project-level learnings go to .claude/rules/aristotle-project-learnings.md"
Write-Host ""
