# install.ps1 — Install Aristotle error reflection agent (Windows)
# Usage: powershell -ExecutionPolicy Bypass -File install.ps1

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SkillSrc = $ScriptDir

# OpenCode hardcodes ~/.claude/skills/ as a discovery path (EXTERNAL_DIRS).
# This is the most reliable location — zero configuration needed.
$ClaudeBase = if ($env:CLAUDE_CONFIG_DIR) { $env:CLAUDE_CONFIG_DIR } else { Join-Path $env:USERPROFILE '.claude' }
$OpenCodeConfig = if ($env:OPENCODE_CONFIG_DIR) { $env:OPENCODE_CONFIG_DIR } else { Join-Path $env:USERPROFILE '.config\opencode' }

Write-Host ""
Write-Host "🦉 Aristotle — Error Reflection & Learning Agent" -ForegroundColor Blue
Write-Host "══════════════════════════════════════════════════"
Write-Host ""

# Step 1: Install skill files to ~/.claude/skills/ (reliable auto-discovery path)
$SkillDest = Join-Path $ClaudeBase 'skills\aristotle'
Write-Host "[1/3] Installing Aristotle skill to $SkillDest..." -ForegroundColor Cyan

New-Item -ItemType Directory -Path $SkillDest -Force | Out-Null
Copy-Item (Join-Path $SkillSrc 'SKILL.md') (Join-Path $SkillDest 'SKILL.md') -Force
Write-Host "✓ Skill files installed." -ForegroundColor Green

# Step 2: Initialize learnings file
$LearningsFile = Join-Path $OpenCodeConfig 'aristotle-learnings.md'
if (-not (Test-Path $LearningsFile)) {
    Write-Host "[2/3] Initializing learnings file at $LearningsFile..." -ForegroundColor Cyan
    @"
# Aristotle Learnings (User-Level)

<!-- Auto-generated by Aristotle. Append-only. Do not reorganize. -->
<!-- Rules written here apply across ALL projects. -->

"@ | Set-Content $LearningsFile -Encoding UTF8
    Write-Host "✓ Learnings file created." -ForegroundColor Green
} else {
    Write-Host "[2/3] Learnings file already exists — preserving." -ForegroundColor Cyan
}

# Step 3: Verify
Write-Host "[3/3] Verifying installation..." -ForegroundColor Cyan
$errors = 0

if (-not (Test-Path (Join-Path $SkillDest 'SKILL.md'))) { $errors++; Write-Host "✗ SKILL.md not found" -ForegroundColor Red }
if (-not (Test-Path $LearningsFile)) { $errors++; Write-Host "✗ Learnings file not found" -ForegroundColor Red }

if ($errors -eq 0) {
    Write-Host "✓ All files verified." -ForegroundColor Green
}

Write-Host ""
Write-Host "══════════════════════════════════════════════════"
Write-Host "🦉 Aristotle installed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Usage:"
Write-Host "  • Type /aristotle in any OpenCode session to reflect on errors"
Write-Host "  • When error-correction patterns are detected, the AI will suggest running /aristotle"
Write-Host "  • Learnings are written to $LearningsFile"
Write-Host "  • Project-level learnings go to .opencode\aristotle-project-learnings.md"
Write-Host ""
