#!/usr/bin/env bash
# install-aristotle.sh — Install Aristotle error reflection agent
# Usage: bash install-aristotle.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_SRC="$SCRIPT_DIR"

# Determine OpenCode config directory
OPENCODE_CONFIG="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}"
CLAUDE_CONFIG="$HOME/.claude"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo "🦉 Aristotle — Error Reflection & Learning Agent"
echo "══════════════════════════════════════════════════"
echo ""

# Step 1: Install skill to OpenCode skills directory
SKILL_DEST="$OPENCODE_CONFIG/skills/aristotle"
echo -e "${BLUE}[1/4]${NC} Installing Aristotle skill to $SKILL_DEST..."

mkdir -p "$SKILL_DEST/hooks"
cp "$SKILL_SRC/SKILL.md" "$SKILL_DEST/SKILL.md"
cp "$SKILL_SRC/hooks/aristotle-reflector.sh" "$SKILL_DEST/hooks/aristotle-reflector.sh"
cp "$SKILL_SRC/hooks/aristotle-reflector.ps1" "$SKILL_DEST/hooks/aristotle-reflector.ps1"
chmod +x "$SKILL_DEST/hooks/aristotle-reflector.sh"
echo -e "${GREEN}✓${NC} Skill files installed."

# Step 2: Initialize the learnings file
LEARNINGS_FILE="$CLAUDE_CONFIG/rules/aristotle-learnings.md"
if [ ! -f "$LEARNINGS_FILE" ]; then
    echo -e "${BLUE}[2/4]${NC} Initializing learnings file at $LEARNINGS_FILE..."
    mkdir -p "$CLAUDE_CONFIG/rules"
    cat > "$LEARNINGS_FILE" << 'LEARNINGS_INIT'
# Aristotle Learnings (User-Level)

<!-- Auto-generated by Aristotle. Append-only. Do not reorganize. -->
<!-- This file is automatically injected into sessions via the rules-injector hook. -->
<!-- Rules written here apply across ALL projects. -->

LEARNINGS_INIT
    echo -e "${GREEN}✓${NC} Learnings file created."
else
    echo -e "${BLUE}[2/4]${NC} Learnings file already exists at $LEARNINGS_FILE — preserving."
fi

# Step 3: Configure Stop hook (optional, ask user)
echo -e "${BLUE}[3/4]${NC} Configuring Stop hook for auto-detection..."

SETTINGS_FILE="$CLAUDE_CONFIG/settings.json"
HOOK_CMD="bash $SKILL_DEST/hooks/aristotle-reflector.sh"

if [ -f "$SETTINGS_FILE" ]; then
    # Check if Aristotle hook already configured
    if grep -q "aristotle-reflector" "$SETTINGS_FILE" 2>/dev/null; then
        echo -e "${GREEN}✓${NC} Stop hook already configured in $SETTINGS_FILE."
    else
        echo -e "${YELLOW}⚠${NC} $SETTINGS_FILE exists but Aristotle hook not found."
        echo "  To add the Stop hook manually, add this to the 'hooks' section:"
        echo ""
        echo '  "Stop": ['
        echo '    {'
        echo '      "matcher": "",'
        echo '      "hooks": ['
        echo "        {"
        echo '          "type": "command",'
        echo "          \"command\": \"$HOOK_CMD\""
        echo "        }"
        echo "      ]"
        echo "    }"
        echo "  ]"
        echo ""
    fi
else
    echo -e "${YELLOW}⚠${NC} No $SETTINGS_FILE found."
    echo "  Creating with Aristotle Stop hook..."
    mkdir -p "$CLAUDE_CONFIG"
    cat > "$SETTINGS_FILE" << SETTINGS_JSON
{
  "hooks": {
    "Stop": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": "$HOOK_CMD"
          }
        ]
      }
    ]
  }
}
SETTINGS_JSON
    echo -e "${GREEN}✓${NC} Stop hook configured in $SETTINGS_FILE."
fi

# Step 4: Verify installation
echo -e "${BLUE}[4/4]${NC} Verifying installation..."

ERRORS=0

if [ ! -f "$SKILL_DEST/SKILL.md" ]; then
    echo -e "${YELLOW}✗${NC} SKILL.md not found at $SKILL_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$SKILL_DEST/hooks/aristotle-reflector.sh" ]; then
    echo -e "${YELLOW}✗${NC} Reflector script not found"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$LEARNINGS_FILE" ]; then
    echo -e "${YELLOW}✗${NC} Learnings file not found"
    ERRORS=$((ERRORS+1))
fi

if [ "$ERRORS" -eq 0 ]; then
    echo -e "${GREEN}✓${NC} All files verified."
else
    echo -e "${YELLOW}⚠${NC} $ERRORS issues found. Check the paths above."
fi

echo ""
echo "══════════════════════════════════════════════════"
echo -e "${GREEN}🦉 Aristotle installed successfully!${NC}"
echo ""
echo "Usage:"
echo "  • Type /aristotle in any OpenCode session to reflect on errors"
echo "  • The Stop hook will auto-detect error corrections and prompt you"
echo "  • Learnings are written to ~/.claude/rules/aristotle-learnings.md"
echo "  • Project-level learnings go to .claude/rules/aristotle-project-learnings.md"
echo ""
echo "To uninstall:"
echo "  rm -rf $SKILL_DEST"
echo "  Remove the Stop hook from $SETTINGS_FILE"
echo ""
