#!/usr/bin/env bash
# install.sh — Install Aristotle error reflection agent
# Usage: bash install.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_SRC="$SCRIPT_DIR"

# Determine OpenCode skill discovery directory
# OpenCode hardcodes ~/.claude/skills/ as a discovery path (EXTERNAL_DIRS).
# This is the most reliable location — zero configuration needed.
SKILL_BASE="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
OPENCODE_CONFIG="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo "🦉 Aristotle — Error Reflection & Learning Agent"
echo "══════════════════════════════════════════════════"
echo ""

# Step 1: Install skill to ~/.claude/skills/ (reliable auto-discovery path)
SKILL_DEST="$SKILL_BASE/skills/aristotle"
echo -e "${BLUE}[1/3]${NC} Installing Aristotle skill to $SKILL_DEST..."

mkdir -p "$SKILL_DEST"
cp "$SKILL_SRC/SKILL.md" "$SKILL_DEST/SKILL.md"
cp "$SKILL_SRC/REFLECTOR.md" "$SKILL_DEST/REFLECTOR.md"
cp "$SKILL_SRC/REFLECT.md" "$SKILL_DEST/REFLECT.md"
cp "$SKILL_SRC/REVIEW.md" "$SKILL_DEST/REVIEW.md"
echo -e "${GREEN}✓${NC} Skill files installed."

# Step 2: Initialize the learnings file
LEARNINGS_FILE="$OPENCODE_CONFIG/aristotle-learnings.md"
if [ ! -f "$LEARNINGS_FILE" ]; then
    echo -e "${BLUE}[2/3]${NC} Initializing learnings file at $LEARNINGS_FILE..."
    cat > "$LEARNINGS_FILE" << 'LEARNINGS_INIT'
# Aristotle Learnings (User-Level)

<!-- Auto-generated by Aristotle. Append-only. Do not reorganize. -->
<!-- Rules written here apply across ALL projects. -->

LEARNINGS_INIT
    echo -e "${GREEN}✓${NC} Learnings file created."
else
    echo -e "${BLUE}[2/3]${NC} Learnings file already exists at $LEARNINGS_FILE — preserving."
fi

# Step 3: Verify installation
echo -e "${BLUE}[3/3]${NC} Verifying installation..."

ERRORS=0

if [ ! -f "$SKILL_DEST/SKILL.md" ]; then
    echo -e "${YELLOW}✗${NC} SKILL.md not found at $SKILL_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$SKILL_DEST/REFLECTOR.md" ]; then
    echo -e "${YELLOW}✗${NC} REFLECTOR.md not found at $SKILL_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$SKILL_DEST/REFLECT.md" ]; then
    echo -e "${YELLOW}✗${NC} REFLECT.md not found at $SKILL_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$SKILL_DEST/REVIEW.md" ]; then
    echo -e "${YELLOW}✗${NC} REVIEW.md not found at $SKILL_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$LEARNINGS_FILE" ]; then
    echo -e "${YELLOW}✗${NC} Learnings file not found"
    ERRORS=$((ERRORS+1))
fi

if [ "$ERRORS" -eq 0 ]; then
    echo -e "${GREEN}✓${NC} All files verified."
else
    echo -e "${YELLOW}⚠${NC} $ERRORS issues found. Check the paths above."
fi

echo ""
echo "══════════════════════════════════════════════════"
echo -e "${GREEN}🦉 Aristotle installed successfully!${NC}"
echo ""
echo "Usage:"
echo "  • Type /aristotle in any OpenCode session to reflect on errors"
echo "  • When error-correction patterns are detected, the AI will suggest running /aristotle"
echo "  • Learnings are written to $LEARNINGS_FILE"
echo "  • Project-level learnings go to .opencode/aristotle-project-learnings.md"
echo ""
echo "To uninstall:"
echo "  rm -rf $SKILL_DEST"
echo "  rm -f $LEARNINGS_FILE"
echo ""
