#!/usr/bin/env bash
# install.sh — Install Aristotle error reflection agent
# Usage: bash install.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_SRC="$SCRIPT_DIR"

# OpenCode discovers skills via skills.paths in opencode.json (~/.config/opencode/skills/).
OPENCODE_CONFIG="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo "🦉 Aristotle — Error Reflection & Learning Agent"
echo "══════════════════════════════════════════════════"
echo ""

# Step 1: Install skill files (SKILL.md + docs)
SKILL_DEST="$OPENCODE_CONFIG/skills/aristotle"
MCP_DEST="$OPENCODE_CONFIG/aristotle"
echo -e "${BLUE}[1/6]${NC} Installing Aristotle skill to $SKILL_DEST..."

mkdir -p "$SKILL_DEST"
cp "$SKILL_SRC/SKILL.md" "$SKILL_DEST/SKILL.md"

# Protocol files go to MCP dir (SKILL_DIR resolves to MCP install dir at runtime)
mkdir -p "$MCP_DEST"
cp "$SKILL_SRC/REFLECTOR.md" "$MCP_DEST/REFLECTOR.md"
cp "$SKILL_SRC/REFLECT.md" "$MCP_DEST/REFLECT.md"
cp "$SKILL_SRC/REVIEW.md" "$MCP_DEST/REVIEW.md"
cp "$SKILL_SRC/CHECKER.md" "$MCP_DEST/CHECKER.md"
cp "$SKILL_SRC/LEARN.md" "$MCP_DEST/LEARN.md"
echo -e "${GREEN}✓${NC} Skill files installed."

# Step 2: Deploy MCP server files
echo -e "${BLUE}[2/6]${NC} Deploying MCP server to $MCP_DEST..."

mkdir -p "$MCP_DEST/aristotle_mcp"
cp -r "$SKILL_SRC/aristotle_mcp/"* "$MCP_DEST/aristotle_mcp/"
rm -rf "$MCP_DEST/aristotle_mcp/__pycache__"
cp "$SKILL_SRC/pyproject.toml" "$MCP_DEST/pyproject.toml"
cp "$SKILL_SRC/uv.lock" "$MCP_DEST/uv.lock"
cd "$MCP_DEST" && uv sync
echo -e "${GREEN}✓${NC} MCP server deployed."

# Step 3: Initialize the learnings file
LEARNINGS_FILE="$OPENCODE_CONFIG/aristotle-learnings.md"
if [ ! -f "$LEARNINGS_FILE" ]; then
    echo -e "${BLUE}[3/6]${NC} Initializing learnings file at $LEARNINGS_FILE..."
    cat > "$LEARNINGS_FILE" << 'LEARNINGS_INIT'
# Aristotle Learnings (User-Level)

<!-- Auto-generated by Aristotle. Append-only. Do not reorganize. -->
<!-- Rules written here apply across ALL projects. -->

LEARNINGS_INIT
    echo -e "${GREEN}✓${NC} Learnings file created."
else
    echo -e "${BLUE}[3/6]${NC} Learnings file already exists at $LEARNINGS_FILE — preserving."
fi

# Step 4: Verify installation
echo -e "${BLUE}[4/6]${NC} Verifying installation..."

ERRORS=0

if [ ! -f "$SKILL_DEST/SKILL.md" ]; then
    echo -e "${YELLOW}✗${NC} SKILL.md not found at $SKILL_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$MCP_DEST/REFLECTOR.md" ]; then
    echo -e "${YELLOW}✗${NC} REFLECTOR.md not found at $MCP_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$MCP_DEST/REFLECT.md" ]; then
    echo -e "${YELLOW}✗${NC} REFLECT.md not found at $MCP_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$MCP_DEST/REVIEW.md" ]; then
    echo -e "${YELLOW}✗${NC} REVIEW.md not found at $MCP_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$MCP_DEST/CHECKER.md" ]; then
    echo -e "${YELLOW}✗${NC} CHECKER.md not found at $MCP_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$MCP_DEST/pyproject.toml" ]; then
    echo -e "${YELLOW}✗${NC} pyproject.toml not found at $MCP_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -d "$MCP_DEST/aristotle_mcp" ]; then
    echo -e "${YELLOW}✗${NC} aristotle_mcp/ not found at $MCP_DEST"
    ERRORS=$((ERRORS+1))
fi

if [ ! -f "$LEARNINGS_FILE" ]; then
    echo -e "${YELLOW}✗${NC} Learnings file not found"
    ERRORS=$((ERRORS+1))
fi

if [ "$ERRORS" -eq 0 ]; then
    echo -e "${GREEN}✓${NC} All files verified."
else
    echo -e "${YELLOW}⚠${NC} $ERRORS issues found. Check the paths above."
fi

# Step 5: Build and deploy Bridge Plugin (optional)
BRIDGE_DEST="$OPENCODE_CONFIG/aristotle-bridge"
BRIDGE_SRC="$SKILL_SRC/plugins/aristotle-bridge"
if [ -d "$BRIDGE_SRC" ] && command -v bun &>/dev/null; then
    echo -e "${BLUE}[5/6]${NC} Building Bridge Plugin..."
    cd "$BRIDGE_SRC" && bun install && bun run build
    mkdir -p "$BRIDGE_DEST"
    cp "$BRIDGE_SRC/dist/index.js" "$BRIDGE_DEST/index.js"
    echo -e "${GREEN}✓${NC} Bridge Plugin deployed to $BRIDGE_DEST"
elif [ -d "$BRIDGE_SRC" ]; then
    echo -e "${YELLOW}[5/6]${NC} Skipping Bridge Plugin (bun not found). Install bun to enable async reflection."
else
    echo -e "${BLUE}[5/6]${NC} Skipping Bridge Plugin (source not found)."
fi

# Step 6: Initialize the aristotle-repo
    echo -e "${BLUE}[6/6]${NC} Initializing rule repository..."
if command -v uv &>/dev/null; then
    uv run --project "$MCP_DEST" python -c "from aristotle_mcp.server import init_repo_tool; print(init_repo_tool())"
    echo -e "${GREEN}✓${NC} Rule repository initialized."
else
    echo -e "${YELLOW}⚠${NC} 'uv' not found — skipping rule repository initialization."
    echo -e "${YELLOW}  Install uv (https://docs.astral.sh/uv/) then run:"
    echo -e "${YELLOW}  uv run --project \"$MCP_DEST\" python -c \"from aristotle_mcp.server import init_repo_tool; print(init_repo_tool())\""
fi

echo ""
echo "══════════════════════════════════════════════════"
echo -e "${GREEN}🦉 Aristotle installed successfully!${NC}"
echo ""
echo "Usage:"
echo "  • Type /aristotle in any OpenCode session to reflect on errors"
echo "  • When error-correction patterns are detected, the AI will suggest running /aristotle"
echo "  • Learnings are written to $LEARNINGS_FILE"
echo "  • Project-level learnings go to .opencode/aristotle-project-learnings.md"
echo ""
echo "To uninstall:"
echo "  rm -rf $SKILL_DEST"
echo "  rm -rf $MCP_DEST"
echo "  rm -rf $BRIDGE_DEST"
echo "  rm -f $LEARNINGS_FILE"
echo ""
